### ISSUE TITLE
dialog choices handleInput behavior change

### ISSUE THREAD

**Issue by hundun000** [seleb/bitsy-hacks#418]
In v20, it supported right/enter/space as select. Now it only supports right by the commit 387c29c900dacbb5e5d4fc7a8e5e17fba453f650, which maybe a mistake.

**Comment by seleb** [comment]
this was an intentional regression due to bitsy updates: when bitsy's input handling was updated as part of v8, the specific key handling that allowed for enter/space inputs was removed in favour of abstracting input into virtual buttons for `UP`, `DOWN`, `LEFT`, `RIGHT`, `OK`, and `MENU` ([ref](https://make.bitsy.org/docs/technical/system#button-codes)). although `OK` covers the same purpose in theory, unfortunately the actual implementation is currently "any key", which for dialog options would lead to players accidentally selecting options.
